USE QPPlatformDB
GO

-- ’æµ„≈‰÷√
TRUNCATE TABLE GrowLevelConfig
GO

INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (2, 10, 1000, 0, N'2º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (3, 20, 1000, 0, N'3º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (4, 30, 1000, 0, N'4º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (5, 40, 1000, 0, N'5º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (6, 50, 1000, 0, N'6º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (7, 60, 1000, 0, N'7º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (8, 80, 1000, 0, N'8º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (9, 90, 1000, 0, N'9º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (10, 100, 1000, 0, N'10º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (11, 200, 1000, 5, N'11º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (12, 300, 1000, 5, N'12º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (13, 400, 1000, 5, N'13º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (14, 500, 1000, 5, N'14º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (15, 600, 1000, 5, N'15º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (16, 700, 1000, 5, N'16º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (17, 800, 1000, 5, N'17º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (18, 900, 1000, 5, N'18º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (19, 1100, 1000, 5, N'19º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (20, 1200, 1000, 5, N'20º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (21, 1300, 2000, 10, N'21º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (22, 1400, 2000, 10, N'22º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (23, 1500, 2000, 10, N'23º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (24, 1600, 2000, 10, N'24º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (25, 1700, 2000, 10, N'25º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (26, 1800, 2000, 10, N'26º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (27, 1900, 2000, 10, N'27º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (28, 2000, 2000, 10, N'28º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (29, 2100, 2000, 10, N'29º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (30, 2200, 2000, 10, N'30º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (31, 2300, 3000, 15, N'31º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (32, 2400, 3000, 15, N'32º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (33, 2500, 3000, 15, N'33º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (34, 2600, 3000, 15, N'34º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (35, 2700, 3000, 15, N'35º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (36, 2800, 3000, 15, N'36º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (37, 2900, 3000, 15, N'37º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (38, 3000, 3000, 15, N'38º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (39, 3100, 3000, 15, N'39º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (40, 3200, 3000, 15, N'40º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (41, 3300, 4000, 20, N'41º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (42, 3400, 4000, 20, N'42º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (43, 3500, 4000, 20, N'43º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (44, 3600, 4000, 20, N'44º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (45, 3700, 4000, 20, N'45º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (46, 3800, 4000, 20, N'46º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (47, 3900, 4000, 20, N'47º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (48, 4000, 4000, 20, N'48º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (49, 4100, 4000, 20, N'49º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (50, 4200, 4000, 20, N'50º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (51, 4300, 5000, 30, N'51º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (52, 4400, 5000, 30, N'52º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (53, 4500, 5000, 30, N'53º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (54, 4600, 5000, 30, N'54º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (55, 4700, 5000, 30, N'55º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (56, 4800, 5000, 30, N'56º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (57, 400000, 5000, 30, N'57º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (58, 500000, 5000, 30, N'58º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (59, 800000, 5000, 30, N'59º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (60, 1000000, 5000, 30, N'60º∂≈‰÷√')

GO