//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 ModuleManager.rc 使用
//
#define IDC_SERVICE_ATTRIB              3
#define IDD_SERVER_ITEM                 129
#define IDD_SERVER_WIZARD_MAIN          137
#define IDD_SERVER_OPTION_1             148
#define IDD_SERVER_WIZARD_1             150
#define IDD_SERVER_OPTION_3             151
#define IDC_LOAD_SERVER                 1000
#define IDC_SERVER_NAME                 1001
#define IDC_MODULE_LIST                 1002
#define IDC_SERVER_TYPE                 1008
#define IDC_MIN_ENTER_MEMBER            1009
#define IDC_SERVER_KIND                 1009
#define IDC_TABLE_COUNT                 1010
#define IDC_MAX_ENTER_MEMBER            1010
#define IDC_MAX_PLAYER                  1011
#define IDC_SERVER_PORT                 1012
#define IDC_SERVER_LIST                 1012
#define IDC_SORT_ID                     1013
#define IDC_CELL_SCORE                  1014
#define IDC_RELOAD_LIST                 1014
#define IDC_MODULE_DESCRIBE             1014
#define IDC_SERVER_PORT2                1015
#define IDC_SERVER_PASSWD               1015
#define IDC_CHAIR_COUNT                 1016
#define IDC_MAX_ENTER_MEMBER7           1016
#define IDC_DATABASE_ADDR               1017
#define IDC_DELETE_SERVER               1018
#define IDC_DATABASE_NAME               1018
#define IDC_SERVICE_DLL_NAME            1021
#define IDC_CLIENT_EXE_NAME             1023
#define IDC_GAME_NAME                   1024
#define IDC_RESTRICT_SCORE              1026
#define IDC_REVENUE_RATIO               1027
#define IDC_MIN_ENTER_SCORE             1027
#define IDC_REVENUE_RADIO               1027
#define IDC_MAX_ENTER_SCORE             1028
#define IDC_SERVICE_REVENUE             1028
#define IDC_SERVICE_SCORE               1028
#define IDC_MIN_TABLE_SCORE             1029
#define IDC_AV_SERVER_PORT              1031
#define IDC_CHECK_SERVICE_MODE1         1055
#define IDC_CHECK_SERVICE_MODE2         1056
#define IDC_CHECK_SERVICE_MODE3         1057
#define IDC_LIST_PARAMETER              1064
#define IDC_LAST                        1065
#define IDC_EDIT_ANDROID_COUNT          1065
#define IDC_COMBO_ENTER_HOUR            1066
#define IDC_NEXT                        1067
#define IDC_COMBO_ENTER_MINUTE          1067
#define IDC_COMBO_ENTER_SECOND          1068
#define IDC_COMBO_LEAVE_HOUR            1069
#define IDC_COMBO_LEAVE_MINUTE          1070
#define IDC_COMBO_LEAVE_SECOND          1071
#define IDC_ITEM_FRAME                  1072
#define IDC_EDIT_ENTERINTERVAL_MIN      1072
#define IDC_EDIT_ENTERINTERVAL_MAX      1073
#define IDC_EDIT_LEAVEINTERVAL_MIN      1074
#define IDC_EDIT_LEAVEINTERVAL_MAX      1075
#define IDC_FINISH                      1076
#define IDC_EDIT_SWITCHTABLE_MIN        1076
#define IDC_EDIT_SWITCHTABLE_MAX        1077
#define IDC_EDIT_TAKESCORE_MIN          1078
#define IDC_EDIT_TAKESCORE_MAX          1079
#define IDC_BT_ADD                      1080
#define IDC_BT_MODIFY                   1081
#define IDC_BT_DELETE                   1082
#define IDC_PROMPT                      9000
#define IDD_SERVER_OPTION_2             9001
#define IDC_IMMEDIATE_WRITE_SCORE       9001
#define IDD_SERVER_WIZARD_2             9002
#define IDC_RECORD_GAME_SCORE           9002
#define IDC_RECORD_GAME_TRACK           9003
#define IDD_SERVER_OPTION_4             9003
#define IDC_FORFEND_GAME_CHAT           9006
#define IDD_SERVER_MATCH                9006
#define IDC_ALLOW_DYNAMIC_JOIN          9007
#define IDD_SERVER_OPTION_6             9007
#define IDC_FORFEND_GAME_LOOKON         9008
#define IDC_FORFEND_GAME_ENTER          9009
#define IDC_ALLOW_OFFLINE_TRUSTEE       9010
#define IDC_ALLOW_AVERT_CHEAT_MODE      9011
#define IDC_ALLOW_ANDROID_ATTEND        9012
#define IDC_FORFEND_ROOM_ENTER          9013
#define IDC_FORFEND_WISPER_ON_GAME      9014
#define IDC_TAB_CTRL                    9015
#define IDC_FORFEND_GAME_RULE           9015
#define IDC_ALLOW_ANDROID_SIMULATE      9019
#define IDC_DYNAMIC_CELL_SCORE          9021
#define IDC_GAME_ID                     9021
#define IDC_DISTRIBUTE_ALLOW            9022
#define IDC_STATIC_REVENUE_SERVICE      9022
#define IDC_DISTRIBUTE_LAST_TABLE       9023
#define IDC_DISTRIBUTE_IMMEDIATE        9024
#define IDC_SERVICE_RADIO               9024
#define IDC_MIN_DISTRIBUTE_USER         9025
#define IDC_MATCH_LIST                  9026
#define IDC_MAX_DISTRIBUTE_USER         9028
#define IDC_LOAD_MATCH                  9029
#define IDC_DISTRIBUTE_TIME_SPACE       9031
#define IDC_DELETE_MATCH                9032
#define IDC_DISTRIBUTE_DRAW_COUNT       9033
#define IDC_DISTRIBUTE_SAME_ADDRESS     9034
#define IDC_DISTRIBUTE_START_DELAY      9035
#define IDC_DISTRIBUTE_START_MIN_USER   9036
#define IDC_DISTRIBUTE_DRAW_COUNT3      9037
#define IDC_DISTRIBUTE_START_MAX_USER   9038
#define IDC_EDIT_MATCHNAME              9039
#define IDC_DEF_PUT_SCORE               9040
#define IDC_LOW_PUT_SCORE               9041
#define IDC_WIN_EXP                     9041
#define IDC_EXCHANGE                    9042
#define IDC_EXCHANGE_RATIO              9042
#define IDC__FAIL_EXP                   9042
#define IDC_FAIL_EXP                    9042
#define IDC_GRATUITY                    9043
#define IDC_MAGIC_EXP                   9044

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        9001
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         9042
#define _APS_NEXT_SYMED_VALUE           9000
#endif
#endif
